spring.application.name=pc-mania.app
security.cognito.cliente.issuer=${COGNITO_CLIENT_ISSUER}
security.cognito.cliente.client-id=${COGNITO_CLIENT_ID}
security.cognito.admin.issuer=${COGNITO_ADMIN_ISSUER}
security.cognito.admin.client-id=${COGNITO_ADMIN_CLIENT_ID}
