spring.application.name=pc-mania.app
security.cognito.cliente.issuer=${COGNITO_CLIENT_ISSUER:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_pqE0nHoSx}
security.cognito.cliente.client-id=${COGNITO_CLIENT_ID:7dhrhg6siist6tobgebkg9vau0}
security.cognito.admin.issuer=${COGNITO_ADMIN_ISSUER:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4JT4WDzLO}
security.cognito.admin.client-id=${COGNITO_ADMIN_CLIENT_ID:6givnud69n7mei71fis0583e93}
